blog/urls.py
from django.urls import path

from blog import views

from .feeds import AtomSiteNewsFeed, LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("addarticle/", views.addArticle, name="addarticle"),
    path("article/<slug:post>/", views.detail, name="detail"),
    path("update/<slug:slug>", views.updateArticle, name="update"),
    path("approve/<slug:slug>", views.approve_post, name="approve"),
    path("unpub/", views.list_unpublished, name="unpub"),
    path("tag/<slug:slug>/", views.tagged, name="tagged"),
    path("delete/<slug:slug>", views.deleteArticle, name="delete"),
    path("", views.articles, name="articles"),
    path("like/<slug:slug>", views.LikeView, name="article_like"),
    path("add_catergory/", views.addCategory, name="add_category"),
    path("category/<slug:category_slug>", views.category, name="category"),
    path("search/", views.search_posts, name="post_search"),
]

ourblog/urls.py
# import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from django.urls import include, path


# from rest_framework.authtoken import views

# import blog.views as blog_views
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('debug/', include(debug_toolbar.urls)),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api-token-auth/', views.obtain_auth_token),
    # path(r'api/auth/', include('knox.urls')),
    path("", include("blog.urls", namespace="blog")),
    # path('api/', include('blog_api.urls', namespace='blog_api')),
    path("users/", include("users.urls", namespace="users")),
    path("summernote/", include("django_summernote.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms

# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from django.forms import widgets

from .models import Article, Category, Comment

choices = Category.objects.all().values_list("name", "name")

choice_list = []

for item in choices:
    choice_list.append(item)


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "author", "content", "image", "tags", "category", "snippet"]
        widgets = {
            "category": forms.Select(
                choices=choice_list, attrs={"class": "form-control"}
            ),
            "author": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "value": "",
                    "id": "zayyad",
                    "type": "hidden",
                }
            ),
            "snippet": forms.Textarea(attrs={"class": "form-control"}),
        }


class ApprovalForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("status",)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "slug"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs = {
            "placeholder": "Enter your Name",
            "class": "form-control",
        }
        self.fields["email"].widget.attrs = {
            "placeholder": "Enter your Email",
            "class": "form-control",
        }
        self.fields["body"].widget.attrs = {
            "placeholder": "Comment here...",
            "class": "form-control",
            "rows": "5",
        }


# class PostSearchForm(forms.Form):
#     q = forms.CharField()
#     c = forms.ModelChoiceField(queryset=Category.objects.all().order_by("name"))

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields["c"].label = ""
#         self.fields["c"].required = False
#         self.fields["c"].label = "Category"
#         self.fields["q"].label = "Search For"
#         self.fields["q"].widget.attrs.update({"class": "form-control"})

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

# from users.models import NewUser
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, Q
from django.shortcuts import HttpResponseRedirect, get_object_or_404, redirect, render
from django.template.defaultfilters import slugify
from django.urls import reverse
from taggit.models import Tag
from .models import Article, Category

from .forms import ApprovalForm, ArticleForm, CommentForm, CategoryForm


def check_super(user):
    return user.is_superuser


@login_required
def addCategory(request):
    form = CategoryForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        form.save_m2m()

        messages.success(request, "Category created successfully")
        return redirect("blog:articles")
    context = {
        "form": form,
    }
    return render(request, "blog/addCategory.html", context)


def articles(request, slug=None):
    articles = Article.objects.all().filter(status="published")
    paginator = Paginator(articles, 5)
    page = request.GET.get("page")
    tag = None
    if slug:
        get_object_or_404(Tag, slug=slug)
    # Article.tags.most_common()[:2]
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    context = {
        "articles": articles,
        "tag": tag,
        "page": page,
    }

    return render(request, "blog/articles.html", context)


@login_required
def LikeView(request, slug):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, slug=slug)
        article.likes.add(request.user)
        return redirect("blog:detail", article.slug)
    else:
        messages.error(request, "You must be logged in to like posts.")
        return redirect(reverse("blog:detail", args=[slug]))


def about(request):
    return render(request, "blog/about.html")


@login_required
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {"articles": articles}
    return render(request, "blog/dashboard.html", context)


@login_required
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    common_tags = Article.tags.most_common()[:4]
    if form.is_valid():
        article = form.save(commit=False)
        article.slug = slugify(article.title)
        article.author = request.user
        article.save()
        form.save_m2m()

        messages.success(request, "Article created successfully")
        return redirect("blog:dashboard")
    context = {
        "common_tags": common_tags,
        "form": form,
    }
    return render(request, "blog/addarticle.html", context)


# def detail(request, post):
#     # article = Article.objects.filter(id = id).first()
#     article = get_object_or_404(Article, slug=post, status="published")
#     allcomments = article.comments.filter(active=True)
#     page = request.GET.get("page", 1)

#     paginator = Paginator(allcomments, 10)
#     try:
#         comments = paginator.page(page)
#     except PageNotAnInteger:
#         comments = paginator.page(1)
#     except EmptyPage:
#         comments = paginator.page(paginator.num_pages)
#     article_tags = Article.tags.values_list("id", flat=True)
#     similar_posts = Article.objects.filter(tags__in=article_tags).exclude(id=article.id)
#     similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
#         "-same_tags", "-publish"
#     )[:3]

#     comments = article.comments.filter(active=True)

#     user_comment = None

#     if request.method == "POST":
#         comment_form = CommentForm(request.POST)
#         if comment_form.is_valid():
#             user_comment = comment_form.save(commit=False)
#             user_comment.post = article
#             user_comment.save()
#             return HttpResponseRedirect(request.path_info)
#     else:
#         comment_form = CommentForm()

#     context = {
#         "comments": user_comment,
#         "comments": comments,
#         "comment_form": comment_form,
#         "allcomments": allcomments,
#         "article": article,
#         "similar_posts": similar_posts,
#     }

#     return render(request, "blog/detail.html", context)


def detail(request, post):
    # Retrieve the article by slug and ensure it's published
    article = get_object_or_404(Article, slug=post, status="published")
    allcomments = article.comments.filter(
        active=True, parent=None
    )  # Only top-level comments for pagination

    # Set up pagination for top-level comments
    page = request.GET.get("page", 1)
    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    # Get related posts based on shared tags
    article_tags = article.tags.values_list("id", flat=True)
    similar_posts = Article.objects.filter(tags__in=article_tags).exclude(id=article.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:3]

    user_comment = None
    if request.method == "POST":
        # Handle comment form submission
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = article
            user_comment.save()
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()

    context = {
        "comments": user_comment,  # Paginated top-level comments
        "comments": comments,  # Paginated top-level comments
        "allcomments": allcomments,
        "comment_form": comment_form,  # Form for new comments
        "article": article,  # Current article details
        "similar_posts": similar_posts,  # Articles with similar tags
    }

    return render(request, "blog/detail.html", context)


@user_passes_test(check_super)
@login_required
def list_unpublished(request):
    unpub = Article.unpublished.all()
    return render(request, "blog/list_unpub.html", {"unpub": unpub})


@user_passes_test(check_super)
@login_required
def approve_post(request, slug):
    post = get_object_or_404(Article, slug=slug)
    form = ApprovalForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save()
        messages.success(request, "Article has been Updated")
        return redirect("blog:dashboard")
    return render(request, "blog/approve.html", {"form": form})


@login_required
def updateArticle(request, slug):
    article = get_object_or_404(Article, slug=slug)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request, "Article has been Updated")
        return redirect("blog:dashboard")
    return render(request, "blog/update.html", {"form": form})


@login_required
def deleteArticle(request, slug):
    article = get_object_or_404(Article, slug=slug)

    article.delete()

    messages.success(request, "Article Deleted Successfully")

    return redirect("blog:dashboard")


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Article.tags.most_common()[:4]
    article = Article.objects.filter(tags=tag)
    context = {
        "tag": tag,
        "common_tags": common_tags,
        "article": article,
    }
    return render(request, "blog/tag_list.html", context)


def category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    article = Article.objects.filter(category=category)

    context = {"category": category, "article": article}

    return render(request, "blog/category.html", context)


def category_list(request):
    category_list = Category.objects.exclude(name="default")
    context = {
        "category_list": category_list,
    }
    return context


# def post_search(request):
#     form = PostSearchForm()
#     q = ""
#     c = ""
#     results = []
#     query = Q()

#     if "q" in request.GET:
#         form = PostSearchForm(request.GET)
#         if form.is_valid():
#             q = form.cleaned_data["q"]
#             c = form.cleaned_data["c"]

#             if c is not None:
#                 query &= Q(category=c)
#             if q is not None:
#                 query &= Q(title__contains=q)

#             results = Article.objects.filter(query)

#     return render(request, "search.html", {"form": form, "q": q, "results": results})


def search_posts(request):
    query = request.GET.get("q")
    if query:
        results = Article.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query)
        )  # Search in title or content
    else:
        results = Article.objects.none()

    return render(request, "search_results.html", {"results": results, "query": query})

templates/blog/addCategory.html
{% extends "base.html" %}
{% block title %}Create a new Category{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
    {% if user.is_authenticated %}
        <h3>Add category</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Post</button>
        </form>
    </div>
    {% else %}
    You're not allowed here. Please go back to main page
    {% endif %}
</div>


{% endblock %}

templates/blog/articles.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
  <main class="tm-main">
      <!-- Search form -->


      <div class="row tm-row">
        {% for post in articles %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
            <a href="{{post.get_absolute_url}}" class="effect-lily tm-post-link tm-pt-60">
                <div class="tm-post-link-inner">
                    <img src="{{post.image.url}}" alt="{{ post.title }}" class="img-fluid">
                </div>
                <div style="display:flex">
                  {% for tag in post.tags.all %}
                  <a href="{% url 'blog:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                  {% endfor %}
              </div>
                <span class="position-absolute tm-new-badge">New</span>
                <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ post.title }}</h2>
            </a>
            <p class="tm-pt-30">
              {{post.snippet|truncatechars:50}}
            </p>
            <div class="d-flex justify-content-between tm-pt-45">
                <span class="tm-color-primary">{{post.tag}}</span>
                <span class="tm-color-primary">{{ post.publish.date }}</span>
            </div>
            <hr>
            <div class="d-flex justify-content-between">
                <span>{{post.total_likes}}</span>
                <span>{{post.author}}</span>
            </div>
        </article>
        {% endfor %}
      </div>
</main>
    <h3 class="text-center">{% include 'pagination.html' with page=articles %}</h3>
{% endblock %}

templates/blog/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
  <main class="tm-main">
<h3>Control Panel</h3>
<hr>
<p>
    Welcome, <small>{{request.user}}</small>
</p>
<hr>
<a class = "btn btn-info" href = "{% url 'blog:addarticle' %}">Add Article </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Date</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.publish.date}}</td>
            <td><a href="{% url 'blog:update' article.slug %}" class = "btn btn-success">Update</a></td>
            <td><a href="{% url 'blog:approve' article.slug %}" class = "btn btn-success">Approve Post</a></td>
            <td><a href="{% url 'blog:delete' article.slug %}" class = "btn btn-danger">Delete</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}
  </main>
</div>

<div class = "alert alert-danger">   
You don't have any articles yet...
</div>
{% endif %}



{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}

<style>
  /* Styling for nested comments */
  .children {
    padding-left: 1.5rem; /* Adds padding to nested comments */
  }

  .nested-comment {
    border-left: 2px solid #ddd; /* Adds a border to visually separate nested comments */
    padding-left: 1.25rem;
    margin-top: 0.5rem;
  }
</style>

<div class="container mx-auto p-4">
  <main class="tm-main">

    <div class="mb-8">
      <img class="w-full rounded-lg" src="{{ article.image.url }}" alt="{{ article.title }}">
    </div>
    

    <div class="lg:flex lg:space-x-8">
      <!-- Main Content Area -->
      <div class="flex-1">
        <h2 class="text-3xl font-semibold text-gray-800 mb-4">{{ article.title }}</h2>
        <p class="text-gray-500 mb-6">Published {{ article.publish.date }} by <strong>{{ article.author.first_name }} {{ article.author.last_name }}</strong></p>
      </div>
      <br/>
      <br/>
        
        <div class="prose lg:prose-lg">{{ article.content|safe }}</div>

        <!-- Like Button with Message Handling -->
        <form action="{% url 'blog:article_like' article.slug %}" method="POST" class="mt-6">
          {% csrf_token %}
          <button type="submit" class="flex items-center px-4 py-2 bg-red-500 text-gray-400 rounded-lg hover:bg-red-600 focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="mr-2" viewBox="0 0 16 16">
              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748z"/>
              <path d="M8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
            </svg>
            {{ article.total_likes }}
          </button>
          {% if messages %}
            <div class="space-y-4 mt-4">
              {% for message in messages %}
                <div class="px-4 py-3 rounded-lg shadow-md {% if message.tags == 'success' %}bg-green-100 text-green-800{% elif message.tags == 'error' %}bg-red-100 text-red-800{% elif message.tags == 'warning' %}bg-yellow-100 text-yellow-800{% elif message.tags == 'info' %}bg-blue-100 text-blue-800{% endif %}">
                  {{ message }}
                </div>
              {% endfor %}
            </div>
          {% endif %}
        </form>

        <!-- Comment Section -->
        {% with allcomments.count as total_comments %}
        <h3 class="text-xl font-semibold mt-8">{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
        {% endwith %}
        
        {% load mptt_tags %}
        <div class="mt-6">
          {% recursetree comments %}
            <div id="{{ node.id }}" class="nested-comment p-4 bg-gray-100 rounded-md">
              <div class="flex justify-between items-center mb-2">
                <span class="font-semibold">{{ node.name }}</span>
                <span class="text-sm text-gray-500">{{ node.publish }}</span>
              </div>
              <div>{{ node.body }}</div>

              {% if node.level < 3 %}
                <button class="text-blue-600 hover:underline mt-2" onclick="myFunction({{ node.id }})">Reply</button>
              {% endif %}
            </div>

            {% if not node.is_leaf_node %}
            <div class="children ml-6">
              {{ children }}
            </div>
            {% endif %}
          {% endrecursetree %}
        </div>

        <div class="py-4">
          <nav aria-label="Page navigation example">
            {% if comments.has_other_pages %}
            <ul class="pagination">
              {% if comments.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
              </li>
              {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
              {% endif %}
              {% for num in comments.paginator.page_range %}
              {% if comments.number == l %}
              <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
              </li>
              {% else %}
              <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
              {% endif %}
              {% endfor %}
              {% if comments.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
              {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
              {% endif %}
            </ul>
            {% endif %}
          </nav>
        </div>

        <!-- Comment Form -->
        <div id="myDIV" class="mt-8">
          <form id="myForm" method="post">
            <h3 class="text-xl font-semibold mb-4">Add a Comment</h3>
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="w-full py-2 px-4 bg-blue-500 text-white rounded-lg hover:bg-blue-600">Submit</button>
          </form>
        </div>
      </div>

      <!-- Sidebar for Similar Posts -->
      <aside class="w-full lg:w-1/3 mt-8 lg:mt-0">
        <div class="bg-white p-6 shadow-md rounded-lg">
          <h3 class="text-lg font-semibold mb-4">Similar Posts</h3>
          <ul>
            {% for similar in similar_posts %}
              <li class="mb-3">
                <a href="{{ similar.get_absolute_url }}" class="text-blue-600 hover:underline">{{ similar.snippet|truncatechars:50 }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </aside>
    </div>
  </main>
</div>

<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      `<form id="newForm" class="form-insert py-2" method="post">
        <div class="flex justify-between items-center">
          <h2>Reply:</h2>
          <button type="button" class="text-gray-600 hover:text-gray-900" onclick="formExit()">Close</button>
        </div>
        <input type="text" name="name" class="w-full border rounded p-2 mb-2" placeholder="Name" required>
        <input type="text" name="email" class="w-full border rounded p-2 mb-2" placeholder="Email" required>
        <textarea name="content" class="w-full border rounded p-2 mb-4" rows="4" placeholder="Write your reply..." required></textarea>
        {% csrf_token %}
        <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded-lg">Submit</button>
      </form>`
    );
  }
</script>

{% endblock %}

templates/blog/list_unpub.html
{% extends 'base.html' %}

{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

{% block content %}

<div class="container mx-auto py-8">
    <h1 class="text-3xl font-semibold text-center text-gray-800 mb-8">Unpublished Posts</h1>

    <div class="bg-white shadow rounded-lg overflow-hidden">
        <table class="min-w-full bg-white">
            <thead class="bg-gray-200 border-b-2 border-gray-300">
                <tr>
                    <th class="text-left p-4 text-sm font-semibold text-gray-600">Title</th>
                    <th class="text-left p-4 text-sm font-semibold text-gray-600">Actions</th>
                </tr>
            </thead>
            <tbody>

                <!-- Loop through unpublished posts -->
                {% for post in unpub %}
                <tr class="border-b border-gray-200">
                    <td class="p-4 text-gray-700">{{ post.title }}</td>
                    <td class="p-4">
                        <div class="flex space-x-3">
                            <form action="{% url 'blog:approve' post.slug %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="px-4 py-2 text-white bg-green-500 rounded hover:bg-green-600 focus:outline-none">Publish</button>
                            </form>

                            <form action="{% url 'blog:update' post.slug %}" method="get">
                                {% csrf_token %}
                                <button type="submit" class="px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-600 focus:outline-none">Edit</button>
                            </form>

                            <form action="{% url 'blog:delete' post.slug %}" method="post" onsubmit="return confirm('Are you sure you want to delete this post?');">
                                {% csrf_token %}
                                <button type="submit" class="px-4 py-2 text-white bg-red-500 rounded hover:bg-red-600 focus:outline-none">Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2" class="p-4 text-center text-gray-500">No unpublished posts found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/blog/tag_list.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
  <main class="tm-main">
      <!-- Search form -->


      <div class="row tm-row">
        {% for post in article %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
            <a href="{{post.get_absolute_url}}" class="effect-lily tm-post-link tm-pt-60">
                <div class="tm-post-link-inner">
                    <img src="{{post.image.url}}" alt="{{ post.title }}" class="img-fluid">
                </div>
                <div style="display:flex">
                  {% for tag in post.tags.all %}
                  <a href="{% url 'blog:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                  {% endfor %}
              </div>
                <span class="position-absolute tm-new-badge">New</span>
                <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ post.title }}</h2>
            </a>
            <p class="tm-pt-30">
              {{post.snippet|truncatechars:50}}
            </p>
            <div class="d-flex justify-content-between tm-pt-45">
                <span class="tm-color-primary">{{post.tag}}</span>
                <span class="tm-color-primary">{{ post.publish.date }}</span>
            </div>
            <hr>
            <div class="d-flex justify-content-between">
                <span>{{post.total_likes}}</span>
                <span>{{post.author}}</span>
            </div>
        </article>
        {% endfor %}
      </div>
</main>
    <h3 class="text-center">{% include 'pagination.html' with page=articles %}</h3>
{% endblock %}
{% comment %} <section class="article">
        <div class="container">
          {% for post in articles %}
          <div class="img-position">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card-text-white-bg-primary-mb-3" style="max-width: 18rem;">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:20}}</h2></div>
                  <div class="card-text"><p>{{post.snippet|truncatechars:50}}</p></div> 
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">{{ post.publish.date }}</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
    <section class="pagination">
      <h3 class="text-center">{% include 'pagination.html' with page=articles %}</h3>
    </section>
  
{% endblock %} {% endcomment %}