blog/urls.py
from django.urls import path

from blog import views

from .feeds import AtomSiteNewsFeed, LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("addarticle/", views.addArticle, name="addarticle"),
    path("article/<slug:post>/", views.detail, name="detail"),
    path("update/<slug:slug>", views.updateArticle, name="update"),
    path("approve/<slug:slug>", views.approve_post, name="approve"),
    path("unpub/", views.list_unpublished, name="unpub"),
    path("tag/<slug:slug>/", views.tagged, name="tagged"),
    path("delete/<slug:slug>", views.deleteArticle, name="delete"),
    path("", views.articles, name="articles"),
    path("like/<slug:slug>", views.LikeView, name="article_like"),
    path("add_catergory/", views.addCategory, name="add_category"),
    path("category/<slug:category_slug>", views.category, name="category"),
    path("search/", views.search_posts, name="post_search"),
]

ourblog/urls.py
# import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from django.urls import include, path


# from rest_framework.authtoken import views

# import blog.views as blog_views
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('debug/', include(debug_toolbar.urls)),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api-token-auth/', views.obtain_auth_token),
    # path(r'api/auth/', include('knox.urls')),
    path("", include("blog.urls", namespace="blog")),
    # path('api/', include('blog_api.urls', namespace='blog_api')),
    path("users/", include("users.urls", namespace="users")),
    path("summernote/", include("django_summernote.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("validate_username/", views.validate_username, name="validate_username"),
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.custom_password_reset_done,
        name="password_reset_done",
    ),
    path(
        "password_reset/complete/",
        views.custom_password_reset_complete,
        name="password_reset_complete",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("view_profile", views.view_profile, name="view_profile"),
    # path("profile/", views.profile, name="profile"),
    path("settings/", views.setting, name="settings"),
    path("settings/password/", views.password, name="password"),
    path("social", views.social, name="social"),
    path(
        "login/",
        views.MyLoginView.as_view(),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    # path(
    #     "activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
    #     views.activate,
    #     name="activate",
    # ),
]

templates/acc_active_email.html
{% autoescape off %} Hi {{ user.username }}, Please click on the link to confirm
your registration, http://{{ domain }}{% url 'activate' uidb64=uid token=token
%} {% endautoescape %}

templates/base.html
<!doctype html>
<html lang="en">

  {% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:100,300,400,600" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "fontawesome/css/all.min.css" %}"> <!-- https://fontawesome.com/ -->
  <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
  <link href="{% static 'css/mediumish.css' %}" rel="stylesheet">
  <link href="{% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet">
  {% include "links.html" %}

  <title>{% block title %} Welcome to blog {% endblock %}</title>

</head>

<body>
  
  {% include "navbar.html" %}
  {% block content %}
  {% endblock %}
  {% include 'footer.html' %}
 
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/templatemo-script.js" %}"></script>
</body>

</html>

templates/fb.html
<span class="w3-badge w3-hover-blue facebook-this">
    <a href="{{ facebook_url }}" class="w3-xlarge" target="_blank" title="Share on Facebook"><i class="fa fa-facebook"></i></a>
</span>

templates/footer.html
{% load static %}
{% comment %} <footer id="footer" class="footer">
  <div class="container">
      <p>Follow MDB on social media</p>
      <div class="social-media">
          <a href="https://www.youtube.com/" class="btn btn-primary m-1" role="button"
            rel="nofollow" target="_blank">
            <i class="fab fa-youtube"></i>
          </a>
        
          <a href="https://twitter.com/Herr_Zee" class="btn btn-primary m-1" role="button" rel="nofollow"
            target="_blank">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="https://github.com/zayyadi" class="btn btn-primary m-1" role="button" rel="nofollow"
            target="_blank">
            <i class="fab fa-github"></i>
          </a>
      </div>
    </div>

    <!--Copyright-->
    <div class="copyrights">
      © 2021 Copyright:
      <p> Zayyad </p>
    </div>
    <!--/.Copyright-->

  </footer> {% endcomment %}


<footer class="row tm-row">
  <hr class="col-12">
  <div class="col-md-6 col-12 tm-color-gray">
      Site owner: <a rel="nofollow" target="_parent" href="https://zayy-portfolio.herokuapp.com" class="tm-external-link">Zayyadev</a>
  </div>
    <div class="col-md-6 col-12 tm-color-gray tm-copyright">
        Copyright {% now "Y" %} zayyadev.
    </div> 
</footer>
  

templates/links.html
{% load static %}
<link rel="icon" href="{% static "images/favicon.ico" %}">
{% comment %} <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"> {% endcomment %}

{% comment %} href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/> {% endcomment %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
{% comment %} <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet"> {% endcomment %}
{% comment %} <link href="{% static 'css/style.min.css' %}" rel="stylesheet"> {% endcomment %}
{% comment %} <link href="{% static 'css/header.css' %}" rel="stylesheet"> {% endcomment %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/monokai-sublime.min.css">
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous%7CMerriweather:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static "fontawesome/css/all.min.css" %}"> <!-- https://fontawesome.com/ -->
  <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
  <link href="{% static 'css/mediumish.css' %}" rel="stylesheet">
  <link href="{% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet">

templates/login.html
{%include "navbar.html"%}
{% include "links.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
    <li class="nav-item" role="presentation">
        <a
        class="nav-link active"
        id="tab-login"
        data-mdb-toggle="pill"
        href={% url "login" %}
        role="tab"
        aria-controls="pills-login"
        aria-selected="true"
        >Login</a
        >
    </li>
    <li class="nav-item" role="presentation">
        <a
        class="nav-link"
        id="tab-register"
        data-mdb-toggle="pill"
        href={% url "register" %}
        role="tab"
        aria-controls="pills-register"
        aria-selected="false"
        >Register</a
        >
    </li>
    </ul>
    <!-- Pills navs -->

    <!-- Pills content -->
    <div class="tab-content">
    <div
        class="tab-pane fade show active"
        id="pills-login"
        role="tabpanel"
        aria-labelledby="tab-login"
    >
        <form>
        <div class="text-center mb-3">
            <p>Sign in with:</p>
            <a href="{% url 'social:begin' 'facebook' %}"
                <button type="button" class="btn btn-primary btn-floating mx-1">
                <i class="fab fa-facebook-f"></i>
                </button>
            </a>
            <a href="{% url 'social:begin' 'twitter' %}"
                <button type="button" class="btn btn-primary btn-floating mx-1">
                <i class="fab fa-twitter"></i>
                </button>
            </a>

            <a href="{% url 'social:begin' 'github' %}"
            <button type="button" class="btn btn-primary btn-floating mx-1">
            <i class="fab fa-github"></i>
            </button>
            </a>
        </div>

        <p class="text-center">or:</p>
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                </div>
            </form>
        </div>
        <!-- Register buttons -->
        <div class="text-center">
            <p>Not a member? <a href={% url "register" %}>Register</a></p>
        </div>
    </div>
{% endblock %}
{%include "scripts.html" %}
{% include "footer.html"%}

templates/navbar.html
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}


    <!-- Navbar -->
<header class="bg-white shadow-lg">
    <div class="container mx-auto flex justify-between items-center py-4">
        <!-- Logo and Home -->
        <div class="flex items-center space-x-8">
            <a href="{% url 'blog:articles' %}">
                <img src="{% static 'images/logo_resized.png' %}" alt="Logo" class="h-12 w-12 rounded-full">
            </a>
            <nav class="hidden md:flex space-x-6">
                <a href="{% url 'blog:articles' %}" class="text-lg font-semibold text-gray-700 hover:text-indigo-600">Home</a>
                <a href="{% url 'blog:dashboard' %}" class="text-lg font-semibold text-gray-700 hover:text-indigo-600">Dashboard</a>
                <a href="{% url 'blog:unpub' %}" class="text-lg font-semibold text-gray-700 hover:text-indigo-600">Unpublished Dashboard</a>
                <a href="{% url 'blog:addarticle' %}" class="text-lg font-semibold text-gray-700 hover:text-indigo-600">Add Article</a>
            </nav>
        </div>

        <!-- Search Bar -->
        <div class="relative flex-1 mx-4">
            <input type="text" placeholder="Search..." class="w-full py-2 px-4 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition">
            <span class="absolute inset-y-0 right-4 flex items-center text-gray-500">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-4.35-4.35M18.76 10.23a8.5 8.5 0 11-17 0 8.5 8.5 0 0117 0z" />
                </svg>
            </span>
        </div>

        <!-- Auth Links -->
        <div class="flex items-center space-x-6">
            {% if user.is_authenticated %}
                <!-- If the user is authenticated, show only the Logout button -->
                <a href="{% url 'users:logout' %}" class="text-lg font-semibold text-gray-600 hover:text-indigo-600">Logout</a>
            {% else %}
                <!-- If not authenticated, show Login and Register -->
                <a href="{% url 'users:login' %}" class="text-lg font-semibold text-gray-600 hover:text-indigo-600">Login</a>
                <a href="{% url 'users:register' %}" class="text-lg font-semibold text-gray-600 hover:text-indigo-600">Register</a>
            {% endif %}
            <!-- Responsive Menu Icon for mobile -->
            <div class="md:hidden flex items-center">
                <button class="mobile-menu-button focus:outline-none">
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Mobile Menu -->
    <nav class="mobile-menu hidden md:hidden bg-gray-50 p-4 shadow-lg">
        <a href="{% url 'blog:articles' %}" class="block py-2 text-gray-700 font-semibold hover:text-indigo-600">Home</a>
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="block py-2 bg-indigo-500 text-white rounded-lg hover:bg-indigo-600 transition">Logout</a>
        {% else %}
            <a href="{% url 'users:login' %}" class="block py-2 text-gray-700 font-semibold hover:text-indigo-600">Login</a>
            <a href="{% url 'users:register' %}" class="block py-2 text-gray-700 font-semibold hover:text-indigo-600">Register</a>
        {% endif %}
    </nav>
</header>

<br/>
<br/>
<br/>

<!-- Optional JavaScript for the mobile menu toggle -->
<script>
    const mobileMenuButton = document.querySelector('.mobile-menu-button');
    const mobileMenu = document.querySelector('.mobile-menu');

    mobileMenuButton.addEventListener('click', () => {
        mobileMenu.classList.toggle('hidden');
    });
</script>

templates/pagination.html
{% load static %}
<div class="row tm-row tm-mt-100 tm-mb-75">
    <div class="tm-prev-next-wrapper">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number}}" class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</a>
        {% endif %}
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number}}" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
        {% endif %}
    </div>
    <div class="tm-paging-wrapper">
        <span class="d-inline-block mr-3">Page</span>
        <nav class="tm-paging-nav d-inline-block">
            <ul>
                <li class="tm-paging-item active">
                    Page {{ page.number }} of {{ page.paginator.num_pages }}.
                </li>
                {% for page in page.paginator.pages_range %}
                    <li class="tm-paging-item">
                        <a href="?page={{ page }}" class="mb-2 tm-btn tm-paging-link">{{ page }}</a>
                    </li>
                {% endfor %} 
            </ul>
        </nav>
    </div>
</div>


{% comment %} <div class="">
    <span class="">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number}}">Previous</a>
    {% endif %}

    <span class="">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>

    {% if page.has_next %}
    <a href="?page={{ page.next_page_number}}"> Next</a>
    {% endif %}
    </span>
</div> {% endcomment %}

templates/register.html
{%include "navbar.html"%}
{% include "links.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
    <h2>Signup</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary btn-block mb-4">Sign Up</button>
    </form>
    </div>
</div>

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.js' %}"></script>

    <script>
        $(document).ready(function () {
            // catch the form's submit event
            $('#id_username').keyup(function () {
                // create an AJAX call
                $.ajax({
                    data: $(this).serialize(), // get the form data
                    url: "{% url 'blog:validate_username' %}",
                    // on success
                    success: function (response) {
                        if (response.is_taken == true) {
                            $('#id_username').removeClass('is-valid').addClass('is-invalid');
                            $('#id_username').after('<div class="invalid-feedback d-block" id="usernameError">This username is not available!</div>')
                        }
                        else {
                            $('#id_username').removeClass('is-invalid').addClass('is-valid');
                            $('#usernameError').remove();

                        }

                    },
                    // on error
                    error: function (response) {
                        // alert the error if any error occured
                        console.log(response.responseJSON.errors)
                    }
                });

                return false;
            });
        })
    </script>
    {% endblock javascript %}

{%include "scripts.html" %}
{% include "footer.html"%}


{% endblock %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/material-ui/5.0.0-alpha.4/Popper/Popper.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();


</script>

templates/search.html
{% extends "base.html" %}
{% block title %}Search Page{% endblock %}
{% block content %}
<div class="container-fluid">
    <main class="tm-main">

    {% if q %}
    <h1>Posts containing "{{ q }}"

        {% if c %}
        In category "{{ c }}"
        {% endif %}

    </h1>
    <p>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>


    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in results %}
                <div class="col-md-4">
                    <a class="text-dark" href="{{post.get_absolute_url}}">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                                <p class="card-text">{{post.snippet|truncatechars:50}}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <p>There are no results for your query.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</main>


    <p><a href="{% url "blog:post_search" %}" class="btn btn-primary" role="button" aria-disabled="true">New
            Search</a>
    </p>
    {% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input class="btn btn-primary my-1" type="submit" value="Search">
    </form>
    {% endif %}

</div>
{% endblock %}

templates/twt.html
<span class="w3-badge w3-hover-blue tweet-this">
    <a href="{{ tweet_url }}" class="w3-xlarge meta-act-link meta-tweet" target="_blank" title="Share on Twitter"><i class="fa fa-twitter"></i></a>
</span>