blog/urls.py
from django.urls import path

from blog import views

from .feeds import AtomSiteNewsFeed, LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("addarticle/", views.addArticle, name="addarticle"),
    path("article/<slug:post>/", views.detail, name="detail"),
    path("update/<slug:slug>", views.updateArticle, name="update"),
    path("approve/<slug:slug>", views.approve_post, name="approve"),
    path("unpub/", views.list_unpublished, name="unpub"),
    path("tag/<slug:slug>/", views.tagged, name="tagged"),
    path("delete/<slug:slug>", views.deleteArticle, name="delete"),
    path("", views.articles, name="articles"),
    path("like/<slug:slug>", views.LikeView, name="article_like"),
    path("add_catergory/", views.addCategory, name="add_category"),
    path("category/<slug:category_slug>", views.category, name="category"),
    path("search/", views.search_posts, name="post_search"),
]

ourblog/urls.py
# import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from django.urls import include, path


# from rest_framework.authtoken import views

# import blog.views as blog_views
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('debug/', include(debug_toolbar.urls)),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api-token-auth/', views.obtain_auth_token),
    # path(r'api/auth/', include('knox.urls')),
    path("", include("blog.urls", namespace="blog")),
    # path('api/', include('blog_api.urls', namespace='blog_api')),
    path("users/", include("users.urls", namespace="users")),
    path("summernote/", include("django_summernote.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("validate_username/", views.validate_username, name="validate_username"),
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.custom_password_reset_done,
        name="password_reset_done",
    ),
    path(
        "password_reset/complete/",
        views.custom_password_reset_complete,
        name="password_reset_complete",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("view_profile", views.view_profile, name="view_profile"),
    # path("profile/", views.profile, name="profile"),
    path("settings/", views.setting, name="settings"),
    path("settings/password/", views.password, name="password"),
    path("social", views.social, name="social"),
    path(
        "login/",
        views.MyLoginView.as_view(),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    # path(
    #     "activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
    #     views.activate,
    #     name="activate",
    # ),
]

users/models.py
from django.db import models
from ourblog import settings
from PIL import Image
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from users.manager import CustomUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(
        _(
            "first name",
        ),
        max_length=50,
    )
    last_name = models.CharField(
        _(
            "last name",
        ),
        max_length=50,
    )
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.first_name + " " + self.last_name


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_profile"
    )
    email = models.EmailField(
        _("email address"),
        unique=True,
    )
    first_name = models.CharField(
        _(
            "first name",
        ),
        max_length=50,
    )
    last_name = models.CharField(
        _(
            "last name",
        ),
        max_length=50,
    )
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")
    about = models.TextField(blank=True)

    def __str__(self):
        return f"{self.user.email} Profile"

    def save(self, *args, **kwargs):

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
        super(Profile, self).save(*args, **kwargs)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(
            user=instance,
            first_name=instance.first_name,
            last_name=instance.last_name,
            email=instance.email,
        )


# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def save_profile(sender, instance, **kwargs):
#     instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from users.models import CustomUser, Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image", "about"]


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-500 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-500 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-500 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )

    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)  # Call the parent class's save method
        # Generate the username based on the user's name (you can use your custom function here)
        user.username = self.generate_unique_username(self.cleaned_data["first_name"])
        user.is_active = True
        user.is_staff = False

        if commit:
            user.save()
        return user

    def generate_unique_username(self, name):
        # Convert the user's name to a lowercase username with underscores
        base_username = name.lower().replace(" ", "_")

        # Check if the base_username is unique, if not, append a number until it is
        username = base_username
        count = 1
        while CustomUser.objects.filter(first_name=username).exists():
            username = f"{base_username}{count}"
            count += 1

        return username


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]

users/views.py
from django import views
from django.shortcuts import render, redirect, get_object_or_404

# from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse, reverse_lazy
from ourblog import settings

from .forms import SignUpForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from users.models import Profile
from django.http import JsonResponse
from social_django.models import UserSocialAuth
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes


class RegisterView(views.View):
    def get(self, request):
        return render(request, "users/register.html", {"form": SignUpForm()})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect(reverse("users:login"))

        return render(request, "register.html", {"form": form})


class MyLoginView(LoginView):
    template_name = "users/login.html"

    def get_success_url(self):
        redirect_url = self.request.GET.get("next")
        if redirect_url:
            return redirect_url

        return reverse("blog:articles")


def social(request):
    return render(request, "users/social.html")


@login_required
def view_profile(request, user_id):
    user = get_object_or_404(Profile, user_id=user_id)
    return render(request, "users/view_profile.html", {"user": user})


@login_required
def setting(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider="github")
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        twitter_login = user.social_auth.get(provider="twitter")
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider="facebook")
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = user.social_auth.count() > 1 or user.has_usable_password()

    return render(
        request,
        "users/settings.html",
        {
            "github_login": github_login,
            "twitter_login": twitter_login,
            "facebook_login": facebook_login,
            "can_disconnect": can_disconnect,
        },
    )


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == "POST":
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, "Your password was successfully updated!")
            return redirect("password")
        else:
            messages.error(request, "Please correct the error below.")
    else:
        form = PasswordForm(request.user)
    return render(request, "users/password.html", {"form": form})


def validate_username(request):
    """Check username availability"""
    username = request.GET.get("username", None)
    response = {"is_taken": User.objects.filter(username__iexact=username).exists()}
    return JsonResponse(response)


class CustomPasswordResetView(PasswordResetView):
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")

    def send_mail(
        self,
        subject_template_name,
        email_template_name,
        context,
        from_email,
        to_email,
        html_email_template_name=None,
    ):
        # Access the user instance and include it in the context
        context["user"] = self.user
        super().send_mail(
            subject_template_name,
            email_template_name,
            context,
            from_email,
            to_email,
            html_email_template_name,
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        uidb64 = urlsafe_base64_encode(force_bytes(self.user.id))
        token = self.object.token
        reset_url = reverse(
            "users:password_reset_confirm", kwargs={"uidb64": uidb64, "token": token}
        )
        email_body = render_to_string(
            "users/password_reset_email.html",
            {
                "protocol": "http",  # or 'https' depending on your setup
                "domain": "127.0.0.1",  # replace with your actual domain
                "uidb64": uidb64,
                "token": token,
                "reset_url": reset_url,
                "user": self.user,  # include the user instance in the context
            },
        )
        send_mail(
            "Password Reset", email_body, settings.DEFAULT_FROM_EMAIL, [self.user.email]
        )
        messages.success(self.request, "Password reset email sent successfully.")
        return response


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("users:password_reset_complete")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Password successfully reset.")
        return response


def custom_password_reset_done(request):
    # Your custom password reset done view logic
    return render(request, "users/password_reset_done.html")


def custom_password_reset_complete(request):
    # Your custom password reset complete view logic
    return render(request, "users/password_reset_complete.html")


def logout_view(request):
    logout(request)
    return render(request, "users/logout.html")

templates/users/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Your account has successfully created. Please click below link to activate your account

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/users/login.html
{% load static tailwind_tags %}
{% load static %}
{% tailwind_css %}

{% include 'navbar.html' %}


<div class="min-h-screen flex items-center justify-center bg-gray-900">
  <div class="max-w-md w-full space-y-8 p-8 bg-gray-900 shadow-md rounded-lg">
    <h2 class="text-3xl font-semibold text-center text-gray-200">Login</h2>
    
    <form method="post" action="{% url 'users:login' %}" class="mt-8">
      {% csrf_token %}
      
      <!-- Username/Email field -->
      <div class="mb-4">
        <label for="id_username" class="block text-sm font-medium text-gray-300">Username or Email</label>
        <input type="text" id="id_username" name="username" autofocus required
               class="mt-1 p-2 w-full border rounded-md">
      </div>
      
      <!-- Password field -->
      <div class="mb-4">
        <label for="id_password" class="block text-sm font-medium text-gray-300">Password</label>
        <input type="password" id="id_password" name="password" required
               class="mt-1 p-2 w-full border rounded-md">
      </div>
      
      <!-- Remember Me checkbox -->
      <div class="flex items-center justify-between mb-4">
        <div class="flex items-center">
          <input type="checkbox" id="id_remember" name="remember" class="mr-2">
          <label for="id_remember" class="text-sm text-gray-600">Remember me</label>
        </div>
        <a href="{% url 'users:password_reset' %}" class="text-sm text-blue-500">Forgot Password?</a>
      </div>
      
      <!-- Login button -->
      <button type="submit" class="w-full bg-green-500 text-white p-2 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:border-blue-300">
        Log in
      </button>
    </form>

    <div>
      <button class="w-full bg-blue-400 text-white p-2 rounded-lg shadow-lg hover:bg-white-400 focus:outline-none focus:ring focus:border-white-400">
        <a href="{% url 'users:social' %}">Login WIth SOCIALS</a>
      </button>
    </div>
    
    <!-- Registration link -->
    <div class="text-center text-sm text-gray-600 mt-4">
      Don't have an account? <a href="{% url 'users:register' %}" class="text-blue-500">Sign up here</a>.
    </div>
  </div>
</div>

templates/users/password.html
{%include "navbar.html"%}
{% include "links.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <h2>Change Password</h2>
  {% if not user.has_usable_password %}
    <p style="color: red">You have not defined a password yet.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>

{% include "scripts.html" %}
{% include "footer.html" %}

{% endblock %}

templates/users/password_change_done.html
{% extends "../base/base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<script>
    window.location.href = '{% url "accounts:profile" %}';
</script>
{% endif %}

<style>
    .login,
    .image {
        min-height: 100vh;
    }

    .bg-image {
        background-image: url('https://picsum.photos/id/433/1080');
        background-size: cover;
        background-position: center center;
    }

    .container-fluid {
        max-width: 100%;
    }

    body {
        margin-bottom: 0px;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12 bg-light">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">

                            <div class="text-center pt-4">
                                <p class="h4 mb-2 font-weight-bold">Password changed</p>
                                <p class="mb-4">Your password has been successfully changed.</p>
                            </div>

                            <p class="small text-center pt-4">
                                <a href="{% url "accounts:login" %}">Sign-in?</a>
                            </p>
                            <p class="small text-center">
                                <a href="{% url "accounts:register" %}">Help Center?</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

templates/users/password_change_form.html
{% extends "../base/base.html" %}

{% block title %}Change your password{% endblock %}
{% block content %}
{% include "base/nav-main.html" %}
<style>
    .login-form {
        background-color: #fff;
    }

    .login-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .login-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid my-5 z-depth-1">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <form class="login-form p-4 rounded" method="post">
                    {% csrf_token %}
                    <h1 class="h4 mb-4 font-weight-bold">Change your password</h1>
                    <p>Use the form below to change your password.</p>

                    {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                        Error: Please try again!
                    </div>
                    {% endif %}

                    <label class="small font-weight-bold">{{ form.old_password.label}}</label>
                    {{ form.old_password }}

                    <ul>
                        <li>Your password can’t be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can’t be a commonly used password.</li>
                        <li>Your password can’t be entirely numeric.</li>
                    </ul>

                    <label class="small font-weight-bold">{{ form.new_password1.label}}</label>
                    {{ form.new_password1 }}
                    <label class="small font-weight-bold">{{ form.new_password2.label}}</label>
                    {{ form.new_password2 }}
                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                        value="Change">Submit
                    </button>
                </form>
            </div>
        </div>
    </section>
</div>

{% include "base/footer.html" %}
{% endblock %}

templates/users/password_reset_complete.html
<script>
    window.location.href = '{% url "accounts:login" %}';
</script>

templates/users/password_reset_confirm.html
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

<div class="container mx-auto mt-8">
    <h2 class="text-2xl font-bold mb-4">Enter a New Password</h2>

    <form method="post" action="{% url 'users:password_reset_confirm' uidb64=uidb64 token=token %}" class="max-w-md">
      {% csrf_token %}
      
      <label for="id_new_password1" class="block text-sm font-medium text-gray-700">New Password</label>
      <input type="password" name="new_password1" id="id_new_password1" class="mt-1 p-2 block w-full rounded-md border-gray-300">

      <label for="id_new_password2" class="block text-sm font-medium text-gray-700">Confirm New Password</label>
      <input type="password" name="new_password2" id="id_new_password2" class="mt-1 p-2 block w-full rounded-md border-gray-300">

      <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded mt-4">Reset Password</button>
    </form>
</div>

templates/users/password_reset_done.html
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

  <div class="container mx-auto mt-8">
    <p class="text-lg">An email has been sent to you with further instructions on resetting your password.</p>
  </div>

templates/users/password_reset_form.html
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

<div class="container mx-auto mt-8">
    <h2 class="text-2xl font-bold mb-4">Reset Your Password</h2>

    <form method="post" action="{% url 'users:password_reset' %}" class="max-w-md">
      {% csrf_token %}
      
      <label for="id_email" class="block text-sm font-medium text-gray-700">Email</label>
      <input type="email" name="email" id="id_email" class="mt-1 p-2 block w-full rounded-md border-gray-300">

      <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded mt-4">Reset Password</button>
    </form>
</div>

templates/users/register.html
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

{% include 'navbar.html' %}

<body class="bg-gray-900">
    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Register For Your Account
                    </h1>
                    <form action="{% url 'users:register' %}" method="post" role="form">
                        {% csrf_token %}

                            <div>
                                <label for="{{ form.first_name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-blue-700">First Name</label>
                                {{ form.first_name }}
                                {{ form.first_name.errors }}
                            </div>

                            <div>
                                <label for="{{ form.last_name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-blue-700">Last Name</label>
                                {{ form.last_name }}
                                {{ form.last_name.errors }}
                            </div>

                            <div>
                                <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-blue-700">Email</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>

                            <div>
                                <label for="{{ form.password1.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-blue-700">Password</label>
                                {{ form.password1 }}
                                {{ form.password1.errors }}
                            </div>

                            <div>
                                <label for="{{ form.password2.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-blue-700">Confirm Password</label>
                                {{ form.password2 }}
                                {{ form.password2.errors }}
                            </div>

                            <ul class="form-errors text-danger list-unstyled my-2">
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>

                            <button class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Create My Account</button>
                            <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                                Don’t have an account yet? <a href="{% url 'users:register' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up</a>
                            </p>
                    </form>
                </div>
            </div>    
        </div>
    </section>
</body>

templates/users/settings.html
{%include "navbar.html"%}
{% include "links.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
  <h2>Settings</h2>

  <h3>GitHub</h3>
  {% if github_login %}
    <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/" target="_blank">{{ github_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'github' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from GitHub</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from GitHub</button>
      <p style="color: red">You must <a href="{% url 'users:password' %}">define a password</a> for your account before disconnecting from Github.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
  {% endif %}

  <h3>Twitter</h3>
  {% if twitter_login %}
    <p>Connected as <a href="https://twitter.com/{{ twitter_login.extra_data.access_token.screen_name }}/" target="_blank">@{{ twitter_login.extra_data.access_token.screen_name }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'twitter' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from Twitter</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from Twitter</button>
      <p style="color: red">You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Twitter.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'twitter' %}">Connect to Twitter</a>
  {% endif %}

  <h3>Facebook</h3>
  {% if facebook_login %}
    <p>Connected as <a href="https://facebook.com/{{ facebook_login.extra_data.id }}/" target="_blank">{{ facebook_login.extra_data.id }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'facebook' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from Facebook</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from Facebook</button>
      <p style="color: red">You must <a href="{% url 'users:password' %}">define a password</a> for your account before disconnecting from Facebook.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'facebook' %}">Connect to Facebook</a>
  {% endif %}

  {%include "scripts.html" %}
{% include "footer.html"%}


{% endblock %}

templates/users/view_profile.html
{% extends 'base.html' %}